# Generated by Django 4.0.2 on 2022-03-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
        ('partidos', '0002_partido_season_partido_visit_alter_partido_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_against', models.BooleanField(verbose_name='Gol en contra')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partidos.partido', verbose_name='Partido')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jugadores.jugador', verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'Gol',
                'verbose_name_plural': 'Goles',
            },
        ),
    ]
