# Generated by Django 4.0.1 on 2022-02-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0002_auto_20220219_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporada',
            name='logo',
            field=models.ImageField(default='null', upload_to='temporadas'),
        ),
    ]
