# Generated by Django 4.0.2 on 2022-03-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
